import { Archivo } from "next/font/google";
import { Gabarito } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";

const gabarito = Gabarito({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-gabarito",
});
const archivo = Archivo({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-archivo",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={gabarito.variable + " " + archivo.variable}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
